// Bundles the in-page sources into IIFE strings in src/server/scan/inpage/generated/.
//   node scripts/build-inpage.mjs                    build once
//   node scripts/build-inpage.mjs --watch <command>  build, rebuild on change while <command> runs (pnpm dev)
import { spawn } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { context } from "esbuild";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const INPAGE = path.join(ROOT, "src/server/scan/inpage");
const OUT = path.join(INPAGE, "generated");
const entries = [
  { name: "collector", entry: "collector.src.ts", exportName: "COLLECTOR_SOURCE" },
  { name: "palette", entry: "palette.src.ts", exportName: "PALETTE_SOURCE" },
];

const inside = (dir, file) => file.startsWith(dir + path.sep);

/** In-page code runs inside the scanned page, so it may only import other in-page files. Type-only imports are erased before this runs. */
const inpageOnly = {
  name: "inpage-only",
  setup(build) {
    build.onResolve({ filter: /.*/ }, (args) => {
      if (args.kind === "entry-point") return undefined;
      const file = path.isAbsolute(args.path) || args.path.startsWith(".") ? path.resolve(args.resolveDir, args.path) : "";
      if (file && inside(INPAGE, file) && !inside(OUT, file)) return undefined;
      return {
        errors: [{ text: `In-page code can only import files from src/server/scan/inpage, not "${args.path}". Use "import type" for app types.` }],
      };
    });
  },
};

/** Writes the bundle as a TypeScript module after every successful build. */
const writeModule = (name, exportName) => ({
  name: "write-module",
  setup(build) {
    build.onEnd(async (result) => {
      if (result.errors.length || !result.outputFiles?.length) return;
      const code = result.outputFiles[0].text;
      await writeFile(path.join(OUT, `${name}.ts`), `// Generated by scripts/build-inpage.mjs. Do not edit.\nexport const ${exportName} = ${JSON.stringify(code)};\n`);
    });
  },
});

const [flag, ...command] = process.argv.slice(2);
const watch = flag === "--watch";

await mkdir(OUT, { recursive: true });
const contexts = await Promise.all(
  entries.map(({ name, entry, exportName }) =>
    context({
      absWorkingDir: ROOT,
      entryPoints: [path.join(INPAGE, entry)],
      bundle: true,
      format: "iife",
      platform: "browser",
      target: "chrome120",
      write: false,
      minify: false,
      keepNames: false,
      legalComments: "none",
      logLevel: "warning",
      plugins: [inpageOnly, writeModule(name, exportName)],
    }),
  ),
);

try {
  await Promise.all(contexts.map((ctx) => ctx.rebuild()));
} catch {
  await Promise.all(contexts.map((ctx) => ctx.dispose()));
  process.exit(1);
}
console.log(`inpage bundles written to ${path.relative(ROOT, OUT)}`);

if (!watch) {
  await Promise.all(contexts.map((ctx) => ctx.dispose()));
} else {
  await Promise.all(contexts.map((ctx) => ctx.watch()));
  console.log("watching in-page sources");
  if (command.length) {
    const child = spawn(command[0], command.slice(1), { stdio: "inherit" });
    for (const signal of ["SIGINT", "SIGTERM", "SIGHUP"]) process.on(signal, () => child.kill(signal));
    child.on("exit", async (code, signal) => {
      await Promise.all(contexts.map((ctx) => ctx.dispose()));
      process.exit(code ?? (signal ? 1 : 0));
    });
  }
}
