// Bundles the in-page sources into IIFE strings in src/server/scan/inpage/generated/.
//   node scripts/build-inpage.mjs                    build once
//   node scripts/build-inpage.mjs --watch <command>  build, rebuild on change while <command> runs (pnpm dev)
import { spawn } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { context } from "esbuild";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const INPAGE = path.join(ROOT, "src/server/scan/inpage");
const OUT = path.join(INPAGE, "generated");
const entries = [
  { name: "collector", entry: "collector.src.ts", exportName: "COLLECTOR_SOURCE" },
  { name: "palette", entry: "palette.src.ts", exportName: "PALETTE_SOURCE" },
];

const inside = (dir, file) => file.startsWith(dir + path.sep);

/** In-page code runs inside the scanned page, so it may only import other in-page files. Type-only imports are erased before this runs. */
const inpageOnly = {
  name: "inpage-only",
  setup(build) {
    build.onResolve({ filter: /.*/ }, (args) => {
      if (args.kind === "entry-point") return undefined;
      const file = path.isAbsolute(args.path) || args.path.startsWith(".") ? path.resolve(args.resolveDir, args.path) : "";
      if (file && inside(INPAGE, file) && !inside(OUT, file)) return undefined;
      return {
        errors: [{ text: `In-page code can only import files from src/server/scan/inpage, not "${args.path}". Use "import type" for app types.` }],
      };
    });
  },
};

const writeModule = (name, exportName, code) =>
  writeFile(path.join(OUT, `${name}.ts`), `// Generated by scripts/build-inpage.mjs. Do not edit.\nexport const ${exportName} = ${JSON.stringify(code)};\n`);

let watching = false;

/** In watch mode, writes each successful rebuild. The first build writes nothing until every bundle has built. */
const writeOnRebuild = (name, exportName) => ({
  name: "write-on-rebuild",
  setup(build) {
    build.onEnd(async (result) => {
      if (!watching || result.errors.length || !result.outputFiles?.length) return;
      await writeModule(name, exportName, result.outputFiles[0].text);
    });
  },
});

const [flag, ...command] = process.argv.slice(2);
const watch = flag === "--watch";

await mkdir(OUT, { recursive: true });
const contexts = await Promise.all(
  entries.map(({ name, entry, exportName }) =>
    context({
      absWorkingDir: ROOT,
      entryPoints: [path.join(INPAGE, entry)],
      bundle: true,
      format: "iife",
      platform: "browser",
      target: "chrome120",
      write: false,
      minify: false,
      keepNames: false,
      legalComments: "none",
      logLevel: "warning",
      plugins: [inpageOnly, writeOnRebuild(name, exportName)],
    }),
  ),
);
const dispose = () => Promise.all(contexts.map((ctx) => ctx.dispose()));

// esbuild has already logged the errors of a failed build. Nothing is written unless both bundles build.
const results = await Promise.allSettled(contexts.map((ctx) => ctx.rebuild()));
if (results.some((result) => result.status === "rejected")) {
  await dispose();
  process.exit(1);
}
await Promise.all(entries.map(({ name, exportName }, i) => writeModule(name, exportName, results[i].value.outputFiles[0].text)));
console.log(`inpage bundles written to ${path.relative(ROOT, OUT)}`);

if (!watch) {
  await dispose();
} else {
  watching = true;
  await Promise.all(contexts.map((ctx) => ctx.watch()));
  console.log("watching in-page sources");
  if (command.length) {
    const child = spawn(command[0], command.slice(1), { stdio: "inherit" });
    let forwarded = false;
    let stopping = false;
    const stop = async (code) => {
      if (stopping) return;
      stopping = true;
      await dispose();
      process.exit(code);
    };
    // Ctrl+C reaches the child directly too, so a forwarded signal may be its second one.
    for (const signal of ["SIGINT", "SIGTERM", "SIGHUP"]) {
      process.on(signal, () => {
        forwarded = true;
        child.kill(signal);
      });
    }
    child.on("error", (error) => {
      console.error(`Could not run ${command[0]}: ${error.message}`);
      void stop(1);
    });
    // A child stopped by a signal we forwarded is a normal stop, not a failure.
    child.on("exit", (code, signal) => void stop(signal ? (forwarded ? 0 : 1) : (code ?? 0)));
  }
}
