import { build } from "esbuild";
import { mkdir, writeFile } from "node:fs/promises";

const OUT = "src/server/scan/inpage/generated";
const entries = [
  { name: "collector", entry: "src/server/scan/inpage/collector.src.ts", exportName: "COLLECTOR_SOURCE" },
  { name: "palette", entry: "src/server/scan/inpage/palette.src.ts", exportName: "PALETTE_SOURCE" },
];

await mkdir(OUT, { recursive: true });
for (const { name, entry, exportName } of entries) {
  const result = await build({
    entryPoints: [entry],
    bundle: true,
    format: "iife",
    platform: "browser",
    target: "chrome120",
    write: false,
    minify: false,
    keepNames: false,
    legalComments: "none",
  });
  const code = result.outputFiles[0].text;
  await writeFile(`${OUT}/${name}.ts`, `// Generated by scripts/build-inpage.mjs. Do not edit.\nexport const ${exportName} = ${JSON.stringify(code)};\n`);
}
console.log(`inpage bundles written to ${OUT}`);
